# Use of /** so that the configurations hold for controller
# managers regardless of their namespace. Usefull in multi-robot setups.
/**/controller_manager:
  ros__parameters:
    update_rate: 1000

    # ROS 2 control broadcasters
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    force_torque_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    # LBR ROS 2 control broadcasters
    lbr_state_broadcaster:
      type: lbr_ros2_control/LBRStateBroadcaster

    cartesian_impedance_controller:
      type: cartesian_impedance_controller/CartesianImpedanceController


    motion_control_handle:
      type: cartesian_controller_handles/MotionControlHandle


/**/motion_control_handle:
  ros__parameters:
    end_effector_link: "probe"
    robot_base_link: "lbr_link_0"
    joints:
      - lbr_A1
      - lbr_A2
      - lbr_A3
      - lbr_A4
      - lbr_A5
      - lbr_A6
      - lbr_A7

/**/force_torque_broadcaster:
  ros__parameters:
    frame_id: lbr/lbr_link_ee
    sensor_name: estimated_ft_sensor
    
/**/cartesian_impedance_controller:
  ros__parameters:
    kuka_hw: false
    end_effector_link: "probe"
    robot_base_link: "lbr_link_0"
    ft_sensor_ref_link: "probe"
    compliance_ref_link: "probe"

    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    joints:
      - lbr_A1
      - lbr_A2
      - lbr_A3
      - lbr_A4
      - lbr_A5
      - lbr_A6
      - lbr_A7
    max_impedance_force: 10000.0 # N
    delta_tau_max: 1.0 # Nm
    stiffness:  # w.r.t. compliance_ref_link coordinates
        trans_x: 800.0
        trans_y: 800.0
        trans_z: 800.0
        rot_x: 20.0
        rot_y: 20.0
        rot_z: 20.0
    nullspace_stiffness: 0.0 # 10.0
    compensate_gravity: true
    compensate_coriolis: true


