name: build-ubuntu-22.04-fri-1.16
on:
  pull_request:
    branches:
      - humble
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    uses: ./.github/workflows/build-humble.yml
    with:
      os: ubuntu-22.04
      fri_version: 1.16
